### ISSUE TITLE
Inaccurate Lightcone Pull Chance

### ISSUE THREAD

**Issue by GelatinSoul** [Jose-AE/hsr-warp-calculator#1]
Forgive me but I have never submitted an issue before and I'm unsure if I'm doing it right or how else to tell you about this.

In the code I noticed that the base pull chance for a lightcone and a character are both the same, but in-game pulling for a 5-star lightcone (before soft pity) is a .8% chance, not a .6% chance like the character banner

**Comment by Jose-AE** [comment]
Thanks for pointing it out, I always thought that light cones had the same chance as 5* chars but never verified it, I will fix this as soon as I can

**Comment by Jose-AE** [comment]
Pushed a patch to fix this, and added the ability to select number of simulations, check it out!

**Comment by GelatinSoul** [comment]
🥺 Thank you!!
