### ISSUE TITLE
Could we possibly add "alternate odds"?

### ISSUE THREAD

**Issue by JaneJeon** [Jose-AE/hsr-warp-calculator#2]
In light of this https://twitter.com/hxg_diluc/status/1785960253626171539 where the "50/50" might not actually be a true 50/50 and "75/25" might not actually be a true 75/25, it might be interesting/useful to have like an "alternate odds mode" or something of the likes where we use the "true" win rate to better plan for our pulls.

Thoughts?

**Comment by Jose-AE** [comment]
Thanks for your suggestion! While implementing an "alternate odds mode" could be interesting, it seems like it might cater to a rather niche audience. However, if you're interested in experimenting with the alternate odds, you can clone the repository and tweak the code to fit your needs. Just head to the src/utils/CalculateWarpProbability.ts file to find the warp odds at the top of the file. If you have any questions or need assistance with modifying the code, please don't hesitate to ask!
