### ISSUE TITLE
Soft pity start point for ZZZ w-engines is incorrect

### ISSUE THREAD

**Issue by JustinL163** [Jose-AE/hsr-warp-calculator#4]
Your configuration file has it listed as 64 for the soft pity start for w-engines, but it appears to be actually 65 based on the community submitted data https://zzz.rng.moe/en/tracker/global

**Comment by Jose-AE** [comment]
Thank you for bringing this to my attention! I've just pushed a patch that addresses and resolves the issue. Please let me know if you encounter any further problems, and thanks again for your help in improving the project.
