### ISSUE TITLE
Soft pity cut-off is off-by-one

### ISSUE THREAD

**Issue by Tibowl** [Jose-AE/hsr-warp-calculator#6]
The `softPity`th pull should increase by `baseRate+softPityIncrement` but it wouldn't since `pity-softPity` is 0 in that case.

https://github.com/Jose-AE/hsr-warp-calculator/blob/86e2a33d52ff59615cb7e465493412dc5a19656b/src/util/pull.ts#L21

Noticed this after someone posted a screenshot with your rates (well _technically_ it was a calculator based on this repo's, but same bug) and it didn't match my tools' calculator

**Comment by Jose-AE** [comment]
Thank you for pointing this out! I've just pushed a patch that changed the formula to `pity - softPity + 1` , this should fix the issue. Please let me know if you encounter any further problems, and thanks again for your help in improving the project.
